Update readme
Real-Dev-Squad/discord-slash-commands pull request #11
Opened 2023-01-25 02:16 UTC by RitikJaiswal75

Add basic readme

2023-01-25 02:20 UTC, RitikJaiswal75 commented on src/index.ts
> -  ): Promise<Response> {
Removed these to remove lint warnings

2023-01-25 02:54 UTC, heyrandhir approved these changes

2023-01-25 13:54 UTC, rohan09-raj requested changes
We can

2023-01-25 13:54 UTC, rohan09-raj commented on README.md
> +This bot is written ibn TypeScript and will be hosted on cloudflare workers. Cloudflare workers provide us with a serverless environment to run our code.
Typo, also the sentence can be improved here.
```
The bot is written in
```

2023-01-25 14:22 UTC, heyrandhir approved these changes
LGTM

2023-01-26 05:30 UTC, rohan09-raj approved these changes

2023-01-26 05:31 UTC, merged