Added the header to passed down the API
Real-Dev-Squad/discord-slash-commands pull request #186
Opened 2024-01-13 14:11 UTC by skv93-coder

Date: 13-Jan-23

Developer Name: @skv93-coder 

---

## Issue Ticket Number

## Description

### Documentation Updated?

- [ ] Yes
- [ ] No

### Under Feature Flag

- [ ] Yes
- [x] No

### Database Changes

- [ ] Yes
- [x] No

### Breaking Changes

- [ ] Yes
- [x] No

### Development Tested?

- [x] Yes
- [ ] No

## Screenshots
<details>
<summary>Screenshot 1</summary>

</details>

## Test Coverage
<details>
<summary>Screenshot 1</summary>

</details>

## Additional Notes

2024-01-15 15:35 UTC, ajoykumardas12 approved these changes
Looks good to me.
But I don't have experience with Discord API, please get more approval.

2024-01-15 17:21 UTC, iamitprakash approved these changes

2024-01-15 17:21 UTC, iamitprakash requested changes
add test case status

2024-01-17 05:17 UTC, iamitprakash approved these changes

2024-01-17 05:17 UTC, merged